name: Build iOS App (local)

on:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-14        # or macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - run: npm ci

      - name: 🚀 Build locally with Xcode
        run: eas build --platform ios \
                       --profile development \
                       --local --non-interactive
